### ISSUE TITLE
function fields is not right 

### ISSUE THREAD

**Issue by tablecell** [panique/pdo-debug#3]
for example 

``` A
$arr=array('username'=>'admin','logintime'=>'NOW()');
 $rawsql="select * from user where username=? and logintime <? ";
 echo     show($rawsql,array_values($arr));
```

**Comment by panique** [comment]
Dude, what .... ? Your "question" is written in a horrible and unreadable way, it doesn't make any sense and nobody knows what you want. What is the problem ? Your code example has absolutly nothing to do with the script, there's no PDO inside and is also written in a messy way, so I have a feeling that the problem is 100% on your side.

Please don't comment here again.
